#!/usr/bin/env python3
"""Push the daily Breakfast Ticker to Telegram.

Reads breakfast-feed.json (generated by build_breakfast.py) and posts a
compact, scannable message to a Telegram chat.

Config (environment):
  TELEGRAM_BOT_TOKEN   required — bot token from @BotFather
  TG_CHANNEL            chat_id or @username to post to.
                       Falls back to $TELEGRAM_HOME_CHANNEL if unset.
                       Set TG_CHANNEL to your public channel (bot must be admin)
                       e.g. "@CitizenAgentsTicker".

Usage:  python3 tg_push.py
"""
import json
import os
import sys
import urllib.request
import urllib.parse

REPO = "https://mikelninh.github.io/citizen-agents"
FEED = os.path.join(os.path.dirname(__file__), "breakfast-feed.json")


def load_feed():
    with open(FEED, encoding="utf-8") as fh:
        return json.load(fh)


def esc(s):
    # Telegram HTML parse_mode: only < > & are special; we keep & as-is in
    # normal text (the feed already contains plain text, not HTML).
    return (s or "").replace("<", "&lt;").replace(">", "&gt;")


def build_message(feed):
    date = feed.get("date", "")
    items = feed.get("items", [])[:8]
    lines = [f"☕ <b>Breakfast Ticker — {esc(date)}</b>", ""]
    for i, it in enumerate(items, 1):
        head = it.get("headline") or it.get("de", {}).get("headline", "")
        src = ""
        if it.get("sources"):
            try:
                from urllib.parse import urlparse
                host = urlparse(it["sources"][0]).netloc.replace("www.", "")
                if host.startswith("xn--"):
                    try:
                        import idna
                        host = idna.decode(host)
                    except Exception:
                        pass
                src = " · " + host
            except Exception:
                src = ""
        lines.append(f"{i}. {esc(head)}{src}")
    lines += [
        "",
        f"🔎 Alle Meldungen & Quellen: {REPO}/breakfast.html",
        "🤝 Fragen & Feedback: github.com/mikelninh/citizen-agents/discussions",
        "",
        "<i>Kostenlos. Verifiziert. Keine Paywall vor deinen Rechten.</i>",
    ]
    return "\n".join(lines)


def send(token, chat, text):
    url = f"https://api.telegram.org/bot{token}/sendMessage"
    data = urllib.parse.urlencode({
        "chat_id": chat,
        "text": text,
        "parse_mode": "HTML",
        "disable_web_page_preview": "true",
    }).encode()
    req = urllib.request.Request(url, data=data, method="POST")
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read().decode()


def load_token():
    tok = os.environ.get("TELEGRAM_BOT_TOKEN")
    if tok:
        return tok
    # Fall back to the gateway .env (same machine, owner-only) so cron jobs
    # that don't inherit the gateway env can still send.
    env_path = os.path.expanduser("~/.hermes/.env")
    try:
        with open(env_path, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if line.startswith("#") or "=" not in line:
                    continue
                k, v = line.split("=", 1)
                if k.strip() == "TELEGRAM_BOT_TOKEN":
                    return v.strip().strip('"').strip("'")
    except Exception:
        pass
    return None


def main():
    token = load_token()
    if not token:
        print("ERROR: TELEGRAM_BOT_TOKEN not found (env or ~/.hermes/.env)", file=sys.stderr)
        sys.exit(2)
    chat = os.environ.get("TG_CHANNEL") or os.environ.get("TELEGRAM_HOME_CHANNEL")
    if not chat:
        # try .env for home channel too
        try:
            with open(os.path.expanduser("~/.hermes/.env"), encoding="utf-8") as fh:
                for line in fh:
                    line = line.strip()
                    if line.startswith("TELEGRAM_HOME_CHANNEL="):
                        chat = line.split("=", 1)[1].strip().strip('"').strip("'")
        except Exception:
            pass
    if not chat:
        print("ERROR: TG_CHANNEL / TELEGRAM_HOME_CHANNEL not set", file=sys.stderr)
        sys.exit(2)
    feed = load_feed()
    msg = build_message(feed)
    try:
        resp = send(token, chat, msg)
        print(f"OK sent to {chat}: {len(msg)} chars")
    except Exception as e:
        print(f"ERROR sending: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
